export const ERROR_CODES = {
    "400": "Bad Request",
    "401": "Unauthorized",
    "402": "Payment Required",
    "403": "Forbidden",
    "404": "Not Found",
    "405": "Method Not Allowed",
    "406": "Not Acceptable",
    "407": "Proxy Authentication Required",
    "408": "Request Timeout",
    "409": "Conflict",
    "410": "Gone",
    "411": "Length Required",
    "412": "Precondition Failed",
    "413": "Payload Too Large",
    "414": "URI Too Long",
    "415": "Unsupported Media Type",
    "416": "Range Not Satisfiable",
    "417": "Expectation Failed",
    "418": "I'm a teapot",
    "421": "Misdirected Request",
    "422": "Unprocessable Entity",
    "423": "Locked",
    "424": "Failed Dependency",
    "425": "Too Early",
    "426": "Upgrade Required",
    "427": "Precondition Required",
    "428": "Too Many Requests",
    "429": "Request Header Fields Too Large",
    "431": "Unavailable For Legal Reasons",
    "451": "Unavailable For Legal Reasons",
    "500": "Internal Server Error",
    "501": "Not Implemented",
    "502": "Bad Gateway",
    "503": "Service Unavailable",
    "504": "Gateway Timeout",
    "505": "HTTP Version Not Supported",
    "506": "Variant Also Negotiates",
    "507": "Insufficient Storage",
    "508": "Loop Detected",
    "510": "Not Extended",
    "511": "Network Authentication Required"
}
export const HTTP_CODES = {
    "100": "Continue",
    "101": "Switching Protocols",
    "102": "Processing",
    "200": "OK",
    "201": "Created",
    "202": "Accepted",
    "204": "No Content",
    "205": "Reset Content",
    "206": "Partial Content",
    "300": "Multiple Choices",
    "301": "Moved Permanently",
    "302": "Found",
    "303": "See Other",
    "304": "Not Modified",
    "305": "Use Proxy",
    "307": "Temporary Redirect",
    "308": "Permanent Redirect",
    "400": "Bad Request",
    "401": "Unauthorized",
    "402": "Payment Required",
    "403": "Forbidden",
    "404": "Not Found",
    "405": "Method Not Allowed",
    "406": "Not Acceptable",
    "407": "Proxy Authentication Required",
    "408": "Request Timeout",
    "409": "Conflict",
    "410": "Gone",
    "411": "Length Required",
    "412": "Precondition Failed",
    "413": "Payload Too Large",
    "414": "URI Too Long",
    "415": "Unsupported Media Type",
    "416": "Range Not Satisfiable",
    "417": "Expectation Failed",
    "418": "I'm a teapot",
    "421": "Misdirected Request",
    "422": "Unprocessable Entity",
    "423": "Locked",
    "424": "Failed Dependency",
    "425": "Too Early",
    "426": "Upgrade Required",
    "427": "Precondition Required",
    "428": "Too Many Requests",
    "429": "Request Header Fields Too Large",
    "431": "Unavailable For Legal Reasons",
    "451": "Unavailable For Legal Reasons",
    "500": "Internal Server Error",
    "501": "Not Implemented",
    "502": "Bad Gateway",
    "503": "Service Unavailable",
    "504": "Gateway Timeout",
    "505": "HTTP Version Not Supported",
    "506": "Variant Also Negotiates",
    "507": "Insufficient Storage",
    "508": "Loop Detected",
    "510": "Not Extended",
    "511": "Network Authentication Required"
};

export const UNIX_CODES = {
    "0": "Success",
    "1": "Operation not permitted",
    "2": "No such file or directory",
    "3": "No such process",
    "4": "Interrupted system call",
    "5": "Input/output error",
    "6": "No such device or address",
    "7": "Argument list too long",
    "8": "Exec format error",
    "9": "Bad file descriptor",
    "10": "No child processes",
    "11": "Resource temporarily unavailable",
    "12": "Cannot allocate memory",
    "13": "Permission denied",
    "14": "Bad address",
    "15": "Block device required",
    "16": "Device or resource busy",
    "17": "File exists",
    "18": "Invalid cross-device link",
    "19": "No such device",
    "20": "Not a directory",
    "21": "Is a directory",
    "22": "Invalid argument",
    "23": "Too many open files in system",
    "24": "Too many open files",
    "25": "Inappropriate ioctl for device",
    "26": "Text file busy",
    "27": "File too large",
    "28": "No space left on device",
    "29": "Illegal seek",
    "30": "Read-only file system",
    "31": "Too many links",
    "32": "Broken pipe",
    "33": "Numerical argument out of domain",
    "34": "Result too large"
}
export const WINDOWS_CODES = {
    "0": "Success",
    "1": "Operation not permitted",
    "2": "No such file or directory",
    "3": "No such process",
    "4": "Interrupted system call",
    "5": "Input/output error",
    "6": "No such device or address",
    "7": "Argument list too long",
    "8": "Exec format error",
    "9": "Bad file descriptor",
    "10": "No child processes",
    "11": "Resource temporarily unavailable",
    "12": "Cannot allocate memory",
    "13": "Permission denied",
    "14": "Bad address",
    "15": "Block device required",
    "16": "Device or resource busy",
    "17": "File exists",
    "18": "Invalid cross-device link",
    "19": "No such device",
    "20": "Not a directory",
    "21": "Is a directory",
    "22": "Invalid argument",
    "23": "Too many open files in system",
    "24": "Too many open files",
    "25": "Inappropriate ioctl for device",
    "26": "Text file busy",
    "27": "File too large",
    "28": "No space left on device",
    "29": "Illegal seek",
    "30": "Read-only file system",
    "31": "Too many links",
    "32": "Broken pipe",
    "33": "Numerical argument out of domain",
    "34": "Result too large"
}

export const DB_CODES = {
    "1045": "Access denied for user",
    "1146": "Table doesn't exist",
    "1064": "You have an error in your SQL syntax",
    "1451": "Cannot delete or update a parent row: a foreign key constraint fails",
    "1366": "Incorrect integer value",
    "1062": "Duplicate entry",
    "1136": "Column count doesn't match value count"
}

export const JS_CODES = {
    "0": "No Error",
    "1": "SyntaxError",
    "2": "ReferenceError",
    "3": "TypeError",
    "4": "RangeError",
    "5": "URIError",
    "6": "EvalError",
    "7": "InternalError"
}

export const CUSTOM_API_CODES = {
    "1000": "Invalid Request",
    "1001": "Authentication Failed",
    "1002": "Unauthorized Access",
    "1003": "Resource Not Found",
    "1004": "Invalid Data Format",
    "1005": "Service Temporarily Unavailable",
    "1006": "Permission Denied",
    "1007": "Session Expired",
    "1008": "Too Many Requests",
    "1009": "Server Error",
    "1010": "Feature Not Supported"
}

export const CUSTOM_APPLICATION_CODES = {
    "100": "General Error",
    "101": "Database Connection Failed",
    "102": "Configuration Not Found",
    "103": "Invalid API Key",
    "104": "User Not Found",
    "105": "File Upload Failed",
    "106": "Permission Denied",
    "107": "Authentication Error",
    "108": "Unknown Error"
}

export const BUSINESS_LOGIC_CODES = {
    "3001": "Product Not In Stock",
    "3002": "Invalid Payment Method",
    "3003": "Order Already Processed",
    "3004": "Item Not Available",
    "3005": "Insufficient Funds",
    "3006": "Order Expired",
    "3007": "Invalid Coupon Code"
}
